"""Add class_name and class_section with named FK

Revision ID: 3311717cc7fe
Revises: 7ff0c7ac849d
Create Date: 2025-11-30 22:36:28.333326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3311717cc7fe'
down_revision = '7ff0c7ac849d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('class_section', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_classes_user_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint('fk_classes_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('class_section')
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###
